# Praktikum Pertemuan 3 — Menyiapkan Data Proyek agar Layak dan Aman Dianalisis

**Mata Kuliah:** Exploratory Data Analysis (KMTI21133) — Pertemuan 3  
**Fase PjBL:** Perencanaan  
**Sub-CPMK3:** Mahasiswa mampu merumuskan pertanyaan analisis dari masalah nyata serta memperoleh data
sesuai lisensi sumbernya, serta mengidentifikasi dan menangani data pribadi yang terkandung di dalamnya (C4, A3).

**Cara kerja.** Sel bertanda `# TODO` Anda kerjakan sendiri; setiap TODO disertai *expected output* agar Anda bisa memeriksa jawaban sendiri. Sel Markdown bertanda **Jawaban Anda** diisi dengan tulisan, bukan kode.

**Bagian A–F** dikerjakan di kelas dengan dataset latihan. **Bagian G** dikerjakan bersama tim di luar kelas dengan dataset proyek Anda sendiri, dan hasilnya menjadi isi **M1 (bobot 5%)** yang dikumpulkan sesuai tenggat di LMS.

## Bagian 0 — Persiapan

Dataset latihan: **`peserta_pelatihan_umkm_2025.csv`** — 620 baris, 28 kolom.
Data pendaftaran dan hasil pelatihan UMKM binaan kampus.

> **Catatan penting:** seluruh isi dataset ini **sintetis** dan dibuat untuk latihan. Tidak ada orang nyata di dalamnya.
> Nomor NIK, nomor telepon, dan surel sengaja dibuat dengan pola yang tidak valid. Perlakukan tetap seolah-olah data nyata,
> karena itulah kebiasaan yang sedang kita latih.

In [ ]:
import pandas as pd
import numpy as np
import hashlib, os

pd.set_option('display.max_columns', 40)
pd.set_option('display.width', 140)
print('pandas', pd.__version__)

pandas 2.2.3

In [ ]:
FILE = 'peserta_pelatihan_umkm_2025.csv'

if not os.path.exists(FILE):
    try:
        from google.colab import files
        files.upload()          # pilih peserta_pelatihan_umkm_2025.csv
    except ImportError:
        raise FileNotFoundError('Letakkan CSV di folder yang sama dengan notebook ini.')

df = pd.read_csv(FILE)
print(df.shape)
df.head(3)

Saving peserta_pelatihan_umkm_2025.csv to peserta_pelatihan_umkm_2025.csv
(620, 28)

,id_peserta,nama_lengkap,nik_dummy,no_hp,email,alamat_jalan,kelurahan,kecamatan,kota,tanggal_lahir,jenis_kelamin,pendidikan_terakhir,status_disabilitas,jumlah_anak,penghasilan_pribadi_bulanan,nama_usaha,kategori_usaha,produk_utama,lama_usaha_tahun,jumlah_karyawan,omzet_usaha_bulanan,pernah_ikut_pelatihan,kanal_pendaftaran,tanggal_daftar,kehadiran_persen,skor_prates,skor_pascates,tingkat_kepuasan
0,PLT-2025-1309,Ratna Hidayat,99991405899249,8.000426e+10,ratna.hidayat@contoh.example,Jl. Cempaka No. 106 RT 02/RW 10,Sukatani,Tapos,Depok,1989-05-14,P,SMP,Tidak,3,500000,CV Mandiri Jaya,Kuliner,Roti dan kue,12.8,4,2950000,Tidak,Datang langsung,2025-04-04,75,52,67.0,5.0
1,PLT-2025-1512,Bunga Santoso,99992410874363,8.000347e+10,bunga.santoso@contoh.example,Jl. Bougenville No. 80 RT 10/RW 02,Mampang,Pancoran Mas,Depok,1987-10-24,P,D3,Tidak,1,950000,Dapur Cahaya Abadi,Jasa Digital,Servis gawai,6.5,3,7750000,Tidak,Formulir daring,2025-02-02,70,59,75.0,4.9
2,PLT-2025-1360,Endah Ramadhan,99991107987303,8.000266e+10,endah.ramadhan@contoh.example,Jl. Anggrek No. 138 RT 07/RW 08,Limo,Limo,Depok,1998-07-11,P,D3,Tidak,2,1500000,Griya Harum Makmur,Kuliner,Katering rumahan,2.5,0,7550000,Tidak,WhatsApp,2025-03-26,90,51,61.0,4.9

---
## Bagian A — Merumuskan pertanyaan analisis

Sebuah pertanyaan analisis dianggap layak bila lolos **tiga uji**:

1. **Uji kolom** — kolom mana yang akan menjawabnya?
2. **Uji bentuk jawaban** — jawabannya berupa angka, peringkat, perbandingan, atau sebaran?
3. **Uji tindak lanjut** — kalau terjawab, apa yang bisa diputuskan?

In [ ]:
# TODO A1 — kenali kolom yang tersedia sebelum menulis pertanyaan
# a. Cetak daftar nama kolom beserta tipe datanya
print(df.dtypes.to_string())

# b. Cetak jumlah baris dan kolom
print(df.shape)

# Expected: 620 baris x 28 kolom

id_peserta                      object
nama_lengkap                    object
nik_dummy                        int64
no_hp                          float64
email                           object
alamat_jalan                    object
kelurahan                       object
kecamatan                       object
kota                            object
tanggal_lahir                   object
jenis_kelamin                   object
pendidikan_terakhir             object
status_disabilitas              object
jumlah_anak                      int64
penghasilan_pribadi_bulanan      int64
nama_usaha                      object
kategori_usaha                  object
produk_utama                    object
lama_usaha_tahun               float64
jumlah_karyawan                  int64
omzet_usaha_bulanan              int64
pernah_ikut_pelatihan           object
kanal_pendaftaran               object
tanggal_daftar                  object
kehadiran_persen                 int64
skor_prates                      int64
skor_pascates                  float64
tingkat_kepuasan               float64
(620, 28)

### TODO A2 — perbaiki tiga pertanyaan berikut

Tulis versi perbaikannya di sel di bawah, beserta kolom yang akan dipakai.

| No | Draf pertanyaan | Masalahnya |
|---|---|---|
| 1 | Bagaimana kondisi peserta pelatihan? | Terlalu kabur |
| 2 | Apakah peserta yang lebih kaya lebih sukses? | "Kaya" dan "sukses" belum didefinisikan sebagai kolom |
| 3 | Apakah pelatihan menaikkan omzet peserta? | Uji kolom gagal — cek sendiri mengapa |

**Jawaban Anda:**

1. Perbaikan: Bagaimana profil demografi peserta pelatihan berdasarkan tingkat pendidikan dan jenis kelamin? — Kolom: pendidikan_terakhir, jenis_kelamin
2. Perbaikan: Apakah peserta dengan penghasilan pribadi bulanan lebih tinggi memiliki omzet usaha bulanan yang lebih besar? — Kolom: penghasilan_pribadi_bulanan, omzet_usaha_bulanan
3. Mengapa uji kolom gagal: Dataset hanya memuat satu kolom omzet saat pendaftaran (omzet_usaha_bulanan) dan tidak memiliki data/kolom omzet sesudah pelatihan, sehingga evaluasi dampak kenaikan omzet tidak dapat diukur.

In [ ]:
# TODO A3 — buktikan jawaban nomor 3 dengan kode
# Periksa apakah ada kolom omzet SESUDAH pelatihan di dataset ini.
# Petunjuk: cari nama kolom yang memuat kata 'omzet'
# Expected: hanya ada satu kolom omzet, yaitu omzet saat mendaftar
kolom_omzet = [col for col in df.columns if 'omzet' in col.lower()]
print(kolom_omzet)

['omzet_usaha_bulanan']

---
## Bagian B — Skala pengukuran

### TODO B1 — klasifikasikan delapan kolom berikut

Isi tabel di sel Markdown ini. Pilihan: **nominal · ordinal · interval · rasio**.

| Kolom | Skala | Alasan singkat |
|---|---|---|
| `kategori_usaha` | **Nominal** | Kategori kualitatif/label jenis usaha tanpa urutan bertingkat |
| `pendidikan_terakhir` | **Ordinal** | Memiliki tingkatan jenjang pendidikan yang berurutan (misal: SD < SMP < SMA < S1) |
| `skor_prates` | **Interval** | Nilai tes numerik yang bisa dibandingkan selisihnya, tetapi tidak memiliki nilai nol mutlak |
| `omzet_usaha_bulanan` | **Rasio** | Nilai uang numerik yang memiliki nilai nol mutlak (Rp 0 berarti tidak ada pendapatan) |
| `jumlah_karyawan` | **Rasio** | Data kuantitatif diskrit dengan nilai nol mutlak (0 berarti tidak ada karyawan) |
| `tingkat_kepuasan` | **Ordinal** | Skala penilaian bertingkat (misal: Sangat Tidak Puas < Puas < Sangat Puas) |
| `tanggal_daftar` | **Interval** | Data tanggal/kalender yang berurutan dan bisa dihitung selisih hari/waktunya, tanpa nol mutlak |
| `kecamatan` | **Nominal** | Label/nama wilayah administratif untuk pengelompokan tanpa tingkatan hirarki numerik |

In [ ]:
# TODO B2 — perbaiki satu kolom ordinal yang salah tipe
# a. Jadikan 'pendidikan_terakhir' bertipe kategori berurutan
#    Urutan: SD < SMP < SMA/SMK < D3 < S1 < S2
urutan_pendidikan = ['SD', 'SMP', 'SMA/SMK', 'D3', 'S1', 'S2']
df['pendidikan_terakhir'] = pd.Categorical(
    df['pendidikan_terakhir'],
    categories=urutan_pendidikan,
    ordered=True
)

# b. Tampilkan value_counts() yang sudah urut menurut jenjang (bukan abjad)
print("=== Value Counts (Urut Jenjang) ===")
print(df['pendidikan_terakhir'].value_counts().sort_index())

# c. Cetak median jenjang pendidikan lewat .cat.codes
# Expected: median = SMA/SMK
median_code = int(df['pendidikan_terakhir'].cat.codes.median())
median_pendidikan = urutan_pendidikan[median_code]

print(f"\nMedian jenjang pendidikan: {median_pendidikan} (kode: {median_code})")

=== Value Counts (Urut Jenjang) ===
pendidikan_terakhir
SD          24
SMP         71
SMA/SMK    281
D3         107
S1         124
S2          13
Name: count, dtype: int64

Median jenjang pendidikan: SMA/SMK (kode: 2)

In [ ]:
# TODO B3 — ubah dua kolom tanggal menjadi bertipe datetime
# Kolom: tanggal_lahir dan tanggal_daftar
# Lalu cetak tanggal pendaftaran paling awal dan paling akhir
# Expected: rentang pendaftaran berada di tahun 2025

# 1. Konversi kedua kolom ke format datetime
df['tanggal_lahir'] = pd.to_datetime(df['tanggal_lahir'])
df['tanggal_daftar'] = pd.to_datetime(df['tanggal_daftar'])

# 2. Cari tanggal pendaftaran paling awal dan paling akhir
tanggal_awal = df['tanggal_daftar'].min()
tanggal_akhir = df['tanggal_daftar'].max()

# 3. Cetak hasil
print(f"Tanggal pendaftaran paling awal : {tanggal_awal.strftime('%Y-%m-%d')}")
print(f"Tanggal pendaftaran paling akhir: {tanggal_akhir.strftime('%Y-%m-%d')}")

Tanggal pendaftaran paling awal : 2025-02-01
Tanggal pendaftaran paling akhir: 2025-05-31

---
## Bagian C — Kamus data

Kamus data adalah satu baris penjelasan untuk setiap kolom. Bangkitkan kerangkanya dengan kode, isi maknanya sendiri.

In [ ]:
# TODO C1 — bangkitkan kerangka kamus data
# Buat DataFrame bernama 'kamus' dengan kolom:
#   nama_kolom, tipe_data, nilai_unik, nilai_kosong, contoh_nilai
# lalu tambahkan empat kolom kosong yang akan diisi manual:
#   deskripsi, skala_pengukuran, kategori_data_pribadi, tindakan_penanganan
# Expected: 28 baris x 9 kolom

kamus_list = []

for col in df.columns:
    # Mengambil contoh nilai pertama yang tidak null/kosong
    sample_val = df[col].dropna().iloc[0] if not df[col].dropna().empty else None

    kamus_list.append({
        'nama_kolom': col,
        'tipe_data': str(df[col].dtype),
        'nilai_unik': df[col].nunique(),
        'nilai_kosong': df[col].isna().sum(),
        'contoh_nilai': sample_val
    })

# Buat DataFrame awal
kamus = pd.DataFrame(kamus_list)

# Tambahkan empat kolom kosong untuk diisi manual
kolom_manual = ['deskripsi', 'skala_pengukuran', 'kategori_data_pribadi', 'tindakan_penanganan']
for col in kolom_manual:
    kamus[col] = None

# Verifikasi bentuk/dimensi
print("Dimensi kamus:", kamus.shape)

# Tampilkan kerangka kamus data
kamus

Dimensi kamus: (28, 9)

,nama_kolom,tipe_data,nilai_unik,nilai_kosong,contoh_nilai,deskripsi,skala_pengukuran,kategori_data_pribadi,tindakan_penanganan
0,id_peserta,object,620,0,PLT-2025-1309,None,None,None,None
1,nama_lengkap,object,450,0,Ratna Hidayat,None,None,None,None
2,nik_dummy,int64,620,0,99991405899249,None,None,None,None
3,no_hp,float64,611,9,80004260813.0,None,None,None,None
4,email,object,450,0,ratna.hidayat@contoh.example,None,None,None,None
5,alamat_jalan,object,620,0,Jl. Cempaka No. 106 RT 02/RW 10,None,None,None,None
6,kelurahan,object,26,0,Sukatani,None,None,None,None
7,kecamatan,object,19,0,Tapos,None,None,None,None
8,kota,object,1,0,Depok,None,None,None,None
9,tanggal_lahir,datetime64[ns],598,0,1989-05-14 00:00:00,None,None,None,None
10,jenis_kelamin,object,2,0,P,None,None,None,None
11,pendidikan_terakhir,category,6,0,SMP,None,None,None,None
12,status_disabilitas,object,2,0,Tidak,None,None,None,None
13,jumlah_anak,int64,5,0,3,None,None,None,None
14,penghasilan_pribadi_bulanan,int64,110,0,500000,None,None,None,None
15,nama_usaha,object,185,0,CV Mandiri Jaya,None,None,None,None
16,kategori_usaha,object,5,0,Kuliner,None,None,None,None
17,produk_utama,object,19,0,Roti dan kue,None,None,None,None
18,lama_usaha_tahun,float64,119,0,12.8,None,None,None,None
19,jumlah_karyawan,int64,11,0,4,None,None,None,None
20,omzet_usaha_bulanan,int64,293,0,2950000,None,None,None,None
21,pernah_ikut_pelatihan,object,2,0,Tidak,None,None,None,None
22,kanal_pendaftaran,object,4,0,Datang langsung,None,None,None,None
23,tanggal_daftar,datetime64[ns],120,0,2025-04-04 00:00:00,None,None,None,None
24,kehadiran_persen,int64,46,0,75,None,None,None,None
25,skor_prates,int64,64,0,52,None,None,None,None
26,skor_pascates,float64,64,34,67.0,None,None,None,None
27,tingkat_kepuasan,float64,28,18,5.0,None,None,None,None

In [ ]:
# TODO C2 — kolom mana yang punya nilai kosong?
# Tampilkan hanya baris kamus yang nilai_kosong-nya lebih dari 0
# Expected: tepat 3 kolom yang punya nilai kosong

kamus_kosong = kamus[kamus['nilai_kosong'] > 0]
kamus_kosong

,nama_kolom,tipe_data,nilai_unik,nilai_kosong,contoh_nilai,deskripsi,skala_pengukuran,kategori_data_pribadi,tindakan_penanganan
3,no_hp,float64,611,9,80004260813.0,None,None,None,None
26,skor_pascates,float64,64,34,67.0,None,None,None,None
27,tingkat_kepuasan,float64,28,18,5.0,None,None,None,None

### TODO C3 — isi kamus untuk lima kolom

Lengkapi tabel berikut. Deskripsi ditulis sebagai kalimat lengkap, bukan pengulangan nama kolom.

| Kolom | Deskripsi | Skala | Satuan |
|---|---|---|---|
| `lama_usaha_tahun` | Durasi waktu operasional usaha milik peserta yang dihitung sejak berdirinya hingga saat pendataan. | Rasio | Tahun |
| `kehadiran_persen` | Tingkat keikutsertaan peserta dalam seluruh rangkaian sesi pelatihan yang diselenggarakan. | Rasio | Persen (%) |
| `skor_pascates` | Nilai hasil evaluasi kemampuan dan pemahaman peserta yang diukur setelah menyelesaikan pelatihan. | Interval | Poin |
| `kanal_pendaftaran` | Media atau sarana yang digunakan oleh peserta untuk melakukan pendaftaran program. | Nominal | - |
| `jumlah_anak` | Banyaknya anak yang menjadi tanggungan hidup dalam keluarga peserta. | Rasio | Orang |

---
## Bagian D — Menandai data pribadi

| Kategori | Artinya |
|---|---|
| **pengenal langsung** | Sendirian sudah menunjuk ke satu orang |
| **quasi-identifier** | Sendirian aman, gabungannya menunjuk ke satu orang |
| **data spesifik** | Bocornya merugikan lebih berat (kesehatan, keuangan pribadi, data anak) |
| **bukan data pribadi** | Tidak menunjuk ke orang; inilah bahan analisis |

In [ ]:
# TODO D1 — susun tabel penandaan Anda sendiri
# Buat dictionary bernama PENANDAAN berisi pasangan:
#     'nama_kolom': ('kategori', 'tindakan')
# Tindakan yang tersedia: 'hapus', 'hash', 'generalisasi', 'pertahankan'
# Kolom yang tidak Anda daftarkan dianggap 'bukan data pribadi' + 'pertahankan'.
#
# Lalu bangun DataFrame 'tanda' dengan kolom: nama_kolom, kategori, tindakan
# dan cetak jumlah kolom per kategori.
# Expected: pengenal langsung >= 5 kolom; data spesifik >= 3 kolom

PENANDAAN = {
    # Pengenal Langsung (Direct Identifier) >= 5 kolom
    'id_peserta': ('pengenal langsung', 'hash'),
    'nama_lengkap': ('pengenal langsung', 'hapus'),
    'nik_dummy': ('pengenal langsung', 'hapus'),
    'no_hp': ('pengenal langsung', 'hapus'),
    'email': ('pengenal langsung', 'hapus'),
    'alamat_jalan': ('pengenal langsung', 'hapus'),

    # Data Spesifik (Sensitive Personal Data) >= 3 kolom
    'status_disabilitas': ('data spesifik', 'pertahankan'),
    'penghasilan_pribadi_bulanan': ('data spesifik', 'generalisasi'),
    'jumlah_anak': ('data spesifik', 'generalisasi'),

    # Quasi-identifier
    'kelurahan': ('quasi-identifier', 'generalisasi'),
    'kecamatan': ('quasi-identifier', 'pertahankan'),
    'kota': ('quasi-identifier', 'pertahankan'),
    'tanggal_lahir': ('quasi-identifier', 'generalisasi'),
    'jenis_kelamin': ('quasi-identifier', 'pertahankan'),
    'pendidikan_terakhir': ('quasi-identifier', 'pertahankan'),
}

# Bangun DataFrame 'tanda'
list_tanda = []
for col in df.columns:
    if col in PENANDAAN:
        kategori, tindakan = PENANDAAN[col]
    else:
        kategori, tindakan = 'bukan data pribadi', 'pertahankan'
    list_tanda.append({
        'nama_kolom': col,
        'kategori': kategori,
        'tindakan': tindakan
    })

tanda = pd.DataFrame(list_tanda)

# Cetak jumlah kolom per kategori
print("=== Jumlah Kolom per Kategori ===")
print(tanda['kategori'].value_counts())

=== Jumlah Kolom per Kategori ===
kategori
bukan data pribadi    13
pengenal langsung      6
quasi-identifier       6
data spesifik          3
Name: count, dtype: int64

### TODO D2 — pertanggungjawabkan tiga keputusan

Tiga kolom berikut sering diperdebatkan. Tulis keputusan Anda **beserta alasannya**.

| Kolom | Kategori pilihan Anda | Tindakan | Alasan |
|---|---|---|---|
| `nama_usaha` | Quasi-identifier | Generalisasi / Redaksi | Nama usaha yang spesifik jika dicari di mesin pencari atau Google Maps dapat dengan mudah dilacak hingga menemukan lokasi dan identitas pemiliknya secara langsung. |
| `omzet_usaha_bulanan` | Data non-pribadi (Atribut Usaha) | Pertahankan | Data ini mencerminkan performa ekonomi/kondisi finansial entitas bisnis, bukan informasi pribadi individu/perorangan. |
| `id_peserta` | Direct Identifier (Pengenal Langsung) | Pseudonimisasi / Hash | Perlu disamarkan agar tidak merujuk ke ID asli peserta, namun nilainya tetap harus unik untuk membedakan antar baris data (primary key) tanpa kehilangan relasinya. |

> Petunjuk untuk `nama_usaha`: bayangkan seseorang mencari nama itu di mesin pencari.
> Petunjuk untuk `omzet_usaha_bulanan`: apakah ini data tentang **orang** atau tentang **usaha**?
> Petunjuk untuk `id_peserta`: apakah Anda masih perlu membedakan satu baris dari baris lain?

---
## Bagian E — Menerapkan tiga tindakan

In [ ]:
# TODO E1 — HAPUS
# Buat DataFrame baru bernama 'aman' yang sudah membuang semua kolom bertindakan 'hapus'.
# Cetak berapa kolom yang dibuang dan berapa yang tersisa.

# Mengambil daftar kolom yang bertindakan 'hapus' dari DataFrame tanda
kolom_dibuang = tanda[tanda['tindakan'] == 'hapus']['nama_kolom'].tolist()

# Membuat salinan DataFrame baru tanpa kolom-kolom tersebut
aman = df.drop(columns=kolom_dibuang).copy()

print(f"Jumlah kolom yang dibuang : {len(kolom_dibuang)} {kolom_dibuang}")
print(f"Jumlah kolom yang tersisa : {aman.shape[1]}")

Jumlah kolom yang dibuang : 5 ['nama_lengkap', 'nik_dummy', 'no_hp', 'email', 'alamat_jalan']
Jumlah kolom yang tersisa : 23

In [ ]:
# TODO E2 — HASH
# Tulis fungsi samarkan(nilai, garam) yang mengembalikan 12 karakter pertama
# dari sha256(garam + nilai). Kembalikan np.nan bila nilainya kosong.
# Terapkan pada kolom yang Anda beri tindakan 'hash'.
# Expected: nilai asli dan hasil hash berbeda, dan nilai asli yang sama menghasilkan hash yang sama

GARAM = 'ganti-dengan-kalimat-rahasia-tim'

def samarkan(nilai, garam=GARAM):
    # Kembalikan NaN jika nilainya kosong (null/None/NaN)
    if pd.isna(nilai):
        return np.nan
    # Gabungkan garam dan nilai, lalu hash dengan SHA-256 dan ambil 12 karakter pertama
    teks = str(garam) + str(nilai)
    return hashlib.sha256(teks.encode('utf-8')).hexdigest()[:12]

# Ambil kolom yang bertindakan 'hash' (misal: 'id_peserta')
kolom_hash = tanda[tanda['tindakan'] == 'hash']['nama_kolom'].tolist()

# Terapkan fungsi samarkan ke kolom tersebut pada DataFrame aman
for kol in kolom_hash:
    aman[kol] = aman[kol].apply(lambda x: samarkan(x, GARAM))

# Tampilkan 5 baris pertama hasil hash
print(f"Kolom yang disamarkan (hash): {kolom_hash}")
aman[kolom_hash].head()

Kolom yang disamarkan (hash): ['id_peserta']

     id_peserta
0  09b72e9a47af
1  565439020ae0
2  2398346a6926
3  97d7aae2281c
4  5695b53f5a0a

In [ ]:
# TODO E3 — buktikan hash bersifat konsisten dan tidak terbaca

nilai_1 = "PLT-2025-1309"
nilai_2 = "PLT-2025-1310"

# a. Hash dua kali nilai yang sama, tunjukkan hasilnya identik

hasil_a1 = samarkan(nilai_1, GARAM)
hasil_a2 = samarkan(nilai_1, GARAM)

print("=== a. Uji Nilai Sama (Konsistensi Determinisme) ===")
print(f"Hash 1 : {hasil_a1}")
print(f"Hash 2 : {hasil_a2}")
print(f"Apakah identik? -> {hasil_a1 == hasil_a2}\n")

# b. Hash dua nilai berbeda, tunjukkan hasilnya berbeda

hasil_b = samarkan(nilai_2, GARAM)

print("=== b. Uji Nilai Berbeda (Collision-Resistant / Keunikan) ===")
print(f"Hash nilai_1 ({nilai_1}): {hasil_a1}")
print(f"Hash nilai_2 ({nilai_2}): {hasil_b}")
print(f"Apakah berbeda? -> {hasil_a1 != hasil_b}")

=== a. Uji Nilai Sama (Konsistensi Determinisme) ===
Hash 1 : 09b72e9a47af
Hash 2 : 09b72e9a47af
Apakah identik? -> True

=== b. Uji Nilai Berbeda (Collision-Resistant / Keunikan) ===
Hash nilai_1 (PLT-2025-1309): 09b72e9a47af
Hash nilai_2 (PLT-2025-1310): d5db20e31394
Apakah berbeda? -> True

**Jawaban Anda:** kalau `GARAM` ikut ter-*commit* ke GitHub, apa yang masih terlindungi dan apa yang tidak?

Yang masih terlindungi: Data yang sudah dibuang permanen (seperti NIK dummy, no HP, alamat, email) tetap aman dan tidak dapat dipulihkan.

Yang tidak terlindungi: Keamanan proses hashing runtuh terhadap HACK. Siapapun yang memiliki dataset dan nilai GARAM dapat mencocokkan atau membuat kamus nilai ID asli secara mudah untuk memetakan kembali identitas asli peserta.

In [ ]:
# TODO E4 — GENERALISASI

ACUAN = pd.Timestamp('2025-09-01')

# a. Hitung usia peserta pada tanggal acuan 1 September 2025

aman['usia'] = (ACUAN.year - aman['tanggal_lahir'].dt.year) - (
    (ACUAN.month < aman['tanggal_lahir'].dt.month) |
    ((ACUAN.month == aman['tanggal_lahir'].dt.month) & (ACUAN.day < aman['tanggal_lahir'].dt.day))
)

# b. Buat kolom 'kelompok_umur' dengan batas: <25, 25-34, 35-44, 45-54, 55+

batas_umur = [-float('inf'), 24, 34, 44, 54, float('inf')]
label_umur = ['<25', '25-34', '35-44', '45-54', '55+']
aman['kelompok_umur'] = pd.cut(aman['usia'], bins=batas_umur, labels=label_umur)

# c. Buang kolom tanggal_lahir dan kelurahan dari 'aman'

aman = aman.drop(columns=['tanggal_lahir', 'kelurahan', 'usia'])

# d. Rapikan kolom kecamatan yang sebagian tertulis KAPITAL

aman['kecamatan'] = aman['kecamatan'].str.strip().str.title()

# Expected: kelompok terbanyak adalah 35-44; kecamatan punya tepat 10 nilai unik

print("=== Distribusi Kelompok Umur ===")
print(aman['kelompok_umur'].value_counts())

print(f"\nJumlah nilai unik kecamatan: {aman['kecamatan'].nunique()}")
print("Daftar kecamatan:", aman['kecamatan'].unique())

=== Distribusi Kelompok Umur ===
kelompok_umur
35-44    267
25-34    153
45-54    108
<25       53
55+       39
Name: count, dtype: int64

Jumlah nilai unik kecamatan: 10
Daftar kecamatan: ['Tapos' 'Pancoran Mas' 'Limo' 'Bojongsari' 'Sukmajaya' 'Cinere' 'Beji'
 'Cimanggis' 'Sawangan' 'Cipayung']

---
## Bagian F — Memeriksa sisa risiko

Menghapus nama belum tentu cukup. Untuk setiap kombinasi quasi-identifier, hitung berapa orang yang punya kombinasi sama. Nilai terkecil disebut **k**. Target kelas ini: **k ≥ 5**.

In [ ]:
# TODO F1 — tulis fungsi cek_k(data, kolom)
# Kembalikan Series berisi: k (grup terkecil), grup berisi 1 orang, total grup

def cek_k(data, kolom):
    # Hitung jumlah anggota untuk setiap kombinasi nilai pada kolom quasi-identifier
    ukuran_grup = data.groupby(kolom, observed=False).size()

    # Ambil hanya grup yang memiliki data (ukuran > 0)
    ukuran_grup = ukuran_grup[ukuran_grup > 0]

    # 1. k = ukuran grup terkecil (minimum group size)
    k = ukuran_grup.min()

    # 2. Banyaknya kombinasi grup yang hanya berisi tepat 1 orang (sangat berisiko teridentifikasi)
    grup_1_orang = (ukuran_grup == 1).sum()

    # 3. Total seluruh grup kombinasi unik yang terbentuk
    total_grup = len(ukuran_grup)

    return pd.Series({
        'k': k,
        'grup_1_orang': grup_1_orang,
        'total_grup': total_grup
    })

In [ ]:
# TODO F2 — ukur risiko SEBELUM penanganan
# Gunakan data asli df dengan kolom:
#   ['kelurahan', 'jenis_kelamin', 'pendidikan_terakhir', 'tanggal_lahir']
# Expected: k = 1 dan SELURUH 620 baris berada di grup berisi satu orang

kolom_sebelum = ['kelurahan', 'jenis_kelamin', 'pendidikan_terakhir', 'tanggal_lahir']

hasil_f2 = cek_k(df, kolom_sebelum)
print(hasil_f2)

k                 1
grup_1_orang    620
total_grup      620
dtype: int64

**Jawaban Anda:** keempat kolom itu tidak memuat nama maupun nomor telepon. Jelaskan dalam dua kalimat mengapa hasilnya tetap berbahaya.

Meskipun tidak ada nama atau nomor telepon, gabungan tanggal lahir, tempat tinggal, gender, dan pendidikan tiap orang di data ini tidak ada yang kembar sama sekali. Siapa pun bisa tahu nama asli pemilik data hanya dengan mencocokkan keempat ciri-ciri tersebut ke data publik lain seperti daftar pemilih (DPT) atau media sosial.

In [ ]:
# TODO F3 — ukur risiko SESUDAH generalisasi
# Gunakan 'aman' dengan kolom:
#   ['kecamatan', 'jenis_kelamin', 'pendidikan_terakhir', 'kelompok_umur']
# Expected: jumlah grup berisi satu orang turun banyak, tetapi k masih 1

kolom_sesudah = ['kecamatan', 'jenis_kelamin', 'pendidikan_terakhir', 'kelompok_umur']

hasil_f3 = cek_k(aman, kolom_sesudah)
print(hasil_f3)

k                 1
grup_1_orang    138
total_grup      266
dtype: int64

In [ ]:
# TODO F4 — TANTANGAN: capai k >= 5
# Generalisasikan lebih jauh sampai k >= 5, dengan MEMPERTAHANKAN sebanyak mungkin informasi.

map_pendidikan = {
    'SD': '< SMA',
    'SMP': '< SMA',
    'SMA/SMK': 'SMA/SMK',
    'D3': 'Perguruan Tinggi',
    'S1': 'Perguruan Tinggi',
    'S2': 'Perguruan Tinggi'
}
aman['pendidikan_gen'] = aman['pendidikan_terakhir'].map(map_pendidikan)

# Anda boleh: memperlebar kelompok umur, menggabungkan kecamatan kecil menjadi 'Lainnya',

map_umur = {
    '<25': '<35',
    '25-34': '<35',
    '35-44': '35-44',
    '45-54': '45+',
    '55+': '45+'
}
aman['kelompok_umur_gen'] = aman['kelompok_umur'].map(map_umur)

# atau mengeluarkan satu kolom dari daftar quasi-identifier.

qi_final = ['jenis_kelamin', 'kelompok_umur_gen', 'pendidikan_gen']

# Catat setiap pilihan dan dampaknya terhadap k.

hasil_f4 = cek_k(aman, qi_final)
print("=== Hasil Pengukuran Risiko (F4) ===")
print(hasil_f4)

print("\n=== Ukuran Seluruh Grup Kombinasi (Terurut) ===")
grup_final = aman.groupby(qi_final, observed=False).size()
print(grup_final.sort_values())

# Petunjuk: ada lebih dari satu jawaban benar. Yang dinilai adalah alasannya.

=== Hasil Pengukuran Risiko (F4) ===
k               11
grup_1_orang     0
total_grup      18
dtype: int64

=== Ukuran Seluruh Grup Kombinasi (Terurut) ===
jenis_kelamin  kelompok_umur_gen  pendidikan_gen
P              45+                < SMA               11
L              45+                < SMA               12
               <35                < SMA               14
               35-44              < SMA               14
P              <35                < SMA               15
L              45+                Perguruan Tinggi    21
P              45+                SMA/SMK             29
               35-44              < SMA               29
L              <35                SMA/SMK             32
                                  Perguruan Tinggi    33
               35-44              Perguruan Tinggi    35
               45+                SMA/SMK             36
P              45+                Perguruan Tinggi    38
               <35                SMA/SMK             52
               35-44              Perguruan Tinggi    57
               <35                Perguruan Tinggi    60
L              35-44              SMA/SMK             61
P              35-44              SMA/SMK             71
dtype: int64

**Jawaban Anda:** tulis kombinasi yang Anda pilih, nilai k yang dicapai, dan informasi apa yang Anda korbankan untuk mencapainya.

- Kombinasi yang dipilih (Quasi-Identifier):

  ['jenis_kelamin', 'kelompok_umur_gen', 'pendidikan_gen']
  - kelompok_umur_gen dikelompokkan menjadi 3 rentang: <35, 35-44, dan 45+
  - pendidikan_gen digabungkan menjadi 3 jenjang: < SMA (SD & SMP), SMA/SMK, dan Perguruan Tinggi (D3, S1, S2).   
  - Kolom kecamatan dikeluarkan dari daftar quasi-identifier.

- Nilai $k$ yang dicapai:$k = 11$ (sudah melampaui target $k \ge 5$), dengan jumlah kelompok berukuran satu orang sebanyak 0 grup.

- Informasi yang dikorbankan (information loss):
  1. Granularitas Geografis: Analisis perbandingan performa atau sebaran UMKM antar-kecamatan di Kota Depok hilang karena kolom kecamatan tidak lagi dipakai dalam pelaporan kombinasi publik.   
  2. Detail Tingkat Pendidikan: Hilangnya kemampuan membedakan lulusan perguruan tinggi (misal D3 vs S1 vs S2) dan sekolah dasar (SD vs SMP) karena telah dilebur ke kategori agregat.   
  3. Presisi Usia: Rentang usia menjadi lebih lebar/kasar (hanya 3 kategori besar), sehingga variasi peserta sangat muda (<25 tahun) atau usia pensiun (55+ tahun) tidak dapat dianalisis secara spesifik lagi.

In [ ]:
# TODO F5 — sel kecil pada tabel agregat
# a. Buat tabel silang jumlah peserta menurut kecamatan x kategori_usaha

tabel_silang = pd.crosstab(aman['kecamatan'], aman['kategori_usaha'])
print("=== Tabel Silang Kecamatan x Kategori Usaha ===")
display(tabel_silang)

# b. Hitung berapa sel yang terisi tetapi berisi kurang dari 5 peserta

mask_sel_kecil = (tabel_silang > 0) & (tabel_silang < 5)
jumlah_sel_kecil = mask_sel_kecil.sum().sum()

print(f"\nJumlah sel yang terisi tetapi berisi kurang dari 5 peserta: {jumlah_sel_kecil} sel")

# Expected: ada sel bernilai 1-4; sel seperti ini tidak boleh ditampilkan apa adanya di laporan

=== Tabel Silang Kecamatan x Kategori Usaha ===

kategori_usaha  Fesyen  Jasa Digital  Kriya  Kuliner  Pertanian
kecamatan
Beji                14            10     15       42          6
Bojongsari           7             5      4       23          2
Cimanggis           16             8     15       44          7
Cinere              16            11      8       23          9
Cipayung             4             6      5       10          1
Limo                10             4     10       15          4
Pancoran Mas        25            12     19       31         12
Sawangan             5             3      3       10          2
Sukmajaya           22            14     11       36         12
Tapos               11             5     11       16          6

Jumlah sel yang terisi tetapi berisi kurang dari 5 peserta: 9 sel

---
## Bagian G — Diterapkan pada proyek tim (dikerjakan di luar kelas)

Bagian ini adalah isi **M1**. Kerjakan bersama tim pada dataset proyek Anda sendiri.

### G1 — Pertanyaan analisis
Tulis **3–5 pertanyaan** yang lolos tiga uji. Untuk setiap pertanyaan, sebutkan kolom yang akan dipakai.

1. Pertanyaan Payung (Utama)

**Pertanyaan**: Bagaimana pergerakan tren likuiditas (volume dan frekuensi transaksi) di pasar saham sepanjang periode pengamatan di tahun 2024?

**Kolom yang dipakai**: Tanggal Perdagangan Terakhir, Volume, Frekuensi

2. Pertanyaan Turunan 1 (Analisis Volatilitas)

**Pertanyaan**: Sepuluh kode saham apa yang memiliki rata-rata selisih harga harian (volatilitas) tertinggi sepanjang tahun?

**Kolom yang dipakai**: Kode Saham, Tertinggi, Terendah (atau menggunakan kolom Selisih)

3. Pertanyaan Turunan 2 (Analisis Asing/Foreign)

**Pertanyaan**: Kode saham apa saja yang mencatatkan akumulasi volume beli asing (Foreign Buy) lebih besar daripada jual asing (Foreign Sell)?

**Kolom yang dipakai**: Kode Saham, Foreign Buy, Foreign Sell

4. Pertanyaan Turunan 3 (Analisis Nilai Transaksi)

**Pertanyaan**: Bagaimana sebaran nilai transaksi (Nilai) pada saham-saham yang ditutup menguat (harga Penutupan lebih besar dari harga Sebelumnya) dibandingkan saham yang melemah?

**Kolom yang dipakai**: Sebelumnya, Penutupan, Nilai

### G2 — Provenans data
Catat lima butir berikut di README repositori tim:

| Butir | Isi |
|---|---|
| Nama sumber | Dataset Ringkasan Perdagangan Harian Saham BEI 2024 (`saham-daily-2024.csv`) |
| Tautan atau nama instansi | Bursa Efek Indonesia (IDX) — https://www.idx.co.id |
| Tanggal pengambilan | 28 September 2026 |
| Lisensi atau nomor surat izin | Open Data / Publikasi Data Statistik Resmi BEI |
| Kalimat sitasi untuk laporan | Bursa Efek Indonesia. (2024). *Ringkasan Perdagangan Harian Saham Indonesia Tahun 2024*. Jakarta: PT Bursa Efek Indonesia. |

### G3 — Kamus data
Isi `TEMPLATE_Kamus_Data.csv` untuk **setiap** kolom dataset tim, termasuk kolom `kategori_data_pribadi` dan `tindakan_penanganan`. Simpan sebagai `data_dictionary.md` atau `.csv` di repositori.

In [6]:
# G4 — jalankan penanganan pada data tim dan periksa nilai k
# Salin pola Bagian E dan F, ganti dataset dan nama kolomnya.
# Simpan hasilnya ke data/processed/ dan JANGAN unggah data/raw/

### G5 — Daftar periksa sebelum `git push`

- [ ] `data/raw/` masuk `.gitignore`
- [ ] Tidak ada nama, NIK, nomor telepon, surel, atau alamat di berkas mana pun
- [ ] Keluaran sel yang sempat menampilkan data pribadi sudah dibersihkan
- [ ] Garam hash tidak tertulis di dalam notebook
- [ ] Kamus data memuat kategori dan tindakan untuk setiap kolom
- [ ] Nilai k pada data yang diunggah sudah dihitung dan dicatat
- [ ] Bila masih ragu: repositori dibuat **privat**

> Menghapus berkas lalu *commit* ulang **tidak** menghilangkan data dari riwayat Git. > Periksa **sebelum** *commit* pertama.