# Praktikum Pertemuan 3 — Menyiapkan Data Proyek agar Layak dan Aman Dianalisis

**Mata Kuliah:** Exploratory Data Analysis (KMTI21133) — Pertemuan 3  
**Fase PjBL:** Perencanaan  
**Sub-CPMK3:** Mahasiswa mampu merumuskan pertanyaan analisis dari masalah nyata serta memperoleh data
sesuai lisensi sumbernya, serta mengidentifikasi dan menangani data pribadi yang terkandung di dalamnya (C4, A3).

**Cara kerja.** Sel bertanda `# TODO` Anda kerjakan sendiri; setiap TODO disertai *expected output* agar Anda bisa memeriksa jawaban sendiri. Sel Markdown bertanda **Jawaban Anda** diisi dengan tulisan, bukan kode.

**Bagian A–F** dikerjakan di kelas dengan dataset latihan. **Bagian G** dikerjakan bersama tim di luar kelas dengan dataset proyek Anda sendiri, dan hasilnya menjadi isi **M1 (bobot 5%)** yang dikumpulkan sesuai tenggat di LMS.

## Bagian 0 — Persiapan

Dataset latihan: **`peserta_pelatihan_umkm_2025.csv`** — 620 baris, 28 kolom.
Data pendaftaran dan hasil pelatihan UMKM binaan kampus.

> **Catatan penting:** seluruh isi dataset ini **sintetis** dan dibuat untuk latihan. Tidak ada orang nyata di dalamnya.
> Nomor NIK, nomor telepon, dan surel sengaja dibuat dengan pola yang tidak valid. Perlakukan tetap seolah-olah data nyata,
> karena itulah kebiasaan yang sedang kita latih.

In [1]:
import pandas as pd
import numpy as np
import hashlib, os

pd.set_option('display.max_columns', 40)
pd.set_option('display.width', 140)
print('pandas', pd.__version__)

pandas 2.2.3

In [4]:
FILE = 'peserta_pelatihan_umkm_2025.csv'

if not os.path.exists(FILE):
    try:
        from google.colab import files
        files.upload()          # pilih peserta_pelatihan_umkm_2025.csv
    except ImportError:
        raise FileNotFoundError('Letakkan CSV di folder yang sama dengan notebook ini.')

df = pd.read_csv(FILE)
print(df.shape)
df.head(3)

Saving peserta_pelatihan_umkm_2025.csv to peserta_pelatihan_umkm_2025.csv
(620, 28)

,id_peserta,nama_lengkap,nik_dummy,no_hp,email,alamat_jalan,kelurahan,kecamatan,kota,tanggal_lahir,jenis_kelamin,pendidikan_terakhir,status_disabilitas,jumlah_anak,penghasilan_pribadi_bulanan,nama_usaha,kategori_usaha,produk_utama,lama_usaha_tahun,jumlah_karyawan,omzet_usaha_bulanan,pernah_ikut_pelatihan,kanal_pendaftaran,tanggal_daftar,kehadiran_persen,skor_prates,skor_pascates,tingkat_kepuasan
0,PLT-2025-1309,Ratna Hidayat,99991405899249,8.000426e+10,ratna.hidayat@contoh.example,Jl. Cempaka No. 106 RT 02/RW 10,Sukatani,Tapos,Depok,1989-05-14,P,SMP,Tidak,3,500000,CV Mandiri Jaya,Kuliner,Roti dan kue,12.8,4,2950000,Tidak,Datang langsung,2025-04-04,75,52,67.0,5.0
1,PLT-2025-1512,Bunga Santoso,99992410874363,8.000347e+10,bunga.santoso@contoh.example,Jl. Bougenville No. 80 RT 10/RW 02,Mampang,Pancoran Mas,Depok,1987-10-24,P,D3,Tidak,1,950000,Dapur Cahaya Abadi,Jasa Digital,Servis gawai,6.5,3,7750000,Tidak,Formulir daring,2025-02-02,70,59,75.0,4.9
2,PLT-2025-1360,Endah Ramadhan,99991107987303,8.000266e+10,endah.ramadhan@contoh.example,Jl. Anggrek No. 138 RT 07/RW 08,Limo,Limo,Depok,1998-07-11,P,D3,Tidak,2,1500000,Griya Harum Makmur,Kuliner,Katering rumahan,2.5,0,7550000,Tidak,WhatsApp,2025-03-26,90,51,61.0,4.9

---
## Bagian A — Merumuskan pertanyaan analisis

Sebuah pertanyaan analisis dianggap layak bila lolos **tiga uji**:

1. **Uji kolom** — kolom mana yang akan menjawabnya?
- kehadiran_persen, skor_prates, skor_pascates

2. **Uji bentuk jawaban** — jawabannya berupa angka, peringkat, perbandingan atau sebaran?
- perbandingan

3. **Uji tindak lanjut** — kalau terjawab, apa yang bisa diputuskan?
- dapat digunakan untuk mengevaluasi apakah kehadiran peserta perlu ditingkatkan dalam pelatihan berikutnya.

In [ ]:
# TODO A1 — kenali kolom yang tersedia sebelum menulis pertanyaan
# a. Cetak daftar nama kolom beserta tipe datanya
print("Daftar Kolom dan Tipe Data:")
print(df.dtypes)

# b. Cetak jumlah baris dan kolom
print("\nJumlah baris dan kolom:")
print(f"{df.shape[0]} baris x {df.shape[1]} kolom")

# Expected: 620 baris x 28 kolom

Jumlah baris dan kolom:
620 baris x 28 kolom

### TODO A2 — perbaiki tiga pertanyaan berikut

Tulis versi perbaikannya di sel di bawah, beserta kolom yang akan dipakai.

| No | Draf pertanyaan | Masalahnya |
|---|---|---|
| 1 | Bagaimana kondisi peserta pelatihan? | Terlalu kabur |
| 2 | Apakah peserta yang lebih kaya lebih sukses? | "Kaya" dan "sukses" belum didefinisikan sebagai kolom |
| 3 | Apakah pelatihan menaikkan omzet peserta? | Uji kolom gagal — cek sendiri mengapa |

**Jawaban Anda:**

1. Perbaikan: _Apakah rata-rata skor pascates peserta lebih tinggi dibandingkan rata-rata skor prates?_ — Kolom: skor_prates dan skor_pascates
2. Perbaikan: _Apakah peserta dengan omzet usaha bulanan yang lebih tinggi memiliki skor pascates yang lebih tinggi?_ — Kolom: omzet_usaha_bulanan dan skor_pascates
3. Mengapa uji kolom gagal: _Karena dataset hanya memiliki omzet_usaha_bulanan sebagai nilai omzet saat data dikumpulkan dan tidak memiliki kolom omzet sebelum dan sesudah pelatihan_

In [ ]:
# TODO A3 — buktikan jawaban nomor 3 dengan kode
# Periksa apakah ada kolom omzet SESUDAH pelatihan di dataset ini.
# Petunjuk: cari nama kolom yang memuat kata 'omzet'
# Expected: hanya ada satu kolom omzet, yaitu omzet saat mendaftar

kolom_omzet = [kolom for kolom in df.columns if 'omzet' in kolom.lower()]

print("Kolom yang memuat kata 'omzet':")
print(kolom_omzet)

Kolom yang memuat kata 'omzet':
['omzet_usaha_bulanan']

---
## Bagian B — Skala pengukuran

### TODO B1 — klasifikasikan delapan kolom berikut

Isi tabel di sel Markdown ini. Pilihan: **nominal · ordinal · interval · rasio**.

| Kolom | Skala | Alasan singkat |
|---|---|---|
| `kategori_usaha` |Nominal |Hanya mengelompokkan kategori tanpa ada tingkatan/urutan |
| `pendidikan_terakhir` |Ordinal |Memiliki tingkatan atau urutan yang jelas |
| `skor_prates` |Interval |Memiliki urutan dan jarak yang bernilai sama/berarti, tetapi nilai nolnya relatif |
| `omzet_usaha_bulanan` |Rasio |Berupa angka numerik dengan nilai nol mutlak |
| `jumlah_karyawan` | Rasio| Berupa data jumlah (hitung) dengan nol mutlak|
| `tingkat_kepuasan` |Ordinal |Memiliki tingkatan bertingkat |
| `tanggal_daftar` |Interval |Berupa data waktu yang memiliki urutan dan rentang/jarak yang jelas |
| `kecamatan` |Nominal |Berupa label/nama lokasi geografis untuk membedakan wilayah tanpa adanya tingkatan |

In [ ]:
# TODO B2 — perbaiki satu kolom ordinal yang salah tipe
# a. Jadikan 'pendidikan_terakhir' bertipe kategori berurutan
#    Urutan: SD < SMP < SMA/SMK < D3 < S1 < S2
kategori_pendidikan = pd.CategoricalDtype(
    categories=['SD', 'SMP', 'SMA/SMK', 'D3', 'S1', 'S2'],
    ordered=True
)
df['pendidikan_terakhir'] = df['pendidikan_terakhir'].astype(kategori_pendidikan)

# b. Tampilkan value_counts() yang sudah urut menurut jenjang (bukan abjad)
print("--- Frekuensi Pendidikan Terakhir (Urut Jenjang) ---")
print(df['pendidikan_terakhir'].value_counts(sort=False))

# c. Cetak median jenjang pendidikan lewat .cat.codes
median_idx = int(df['pendidikan_terakhir'].cat.codes.median())
median_jenjang = df['pendidikan_terakhir'].cat.categories[median_idx]

print(f"\nMedian jenjang pendidikan: {median_jenjang}")

# Expected: median = SMA/SMK

--- Frekuensi Pendidikan Terakhir (Urut Jenjang) ---
pendidikan_terakhir
SD          24
SMP         71
SMA/SMK    281
D3         107
S1         124
S2          13
Name: count, dtype: int64

Median jenjang pendidikan: SMA/SMK

In [ ]:
# TODO B3 — ubah dua kolom tanggal menjadi bertipe datetime
# Kolom: tanggal_lahir dan tanggal_daftar
# Lalu cetak tanggal pendaftaran paling awal dan paling akhir
df['tanggal_lahir'] = pd.to_datetime(df['tanggal_lahir'])
df['tanggal_daftar'] = pd.to_datetime(df['tanggal_daftar'])

tgl_awal = df['tanggal_daftar'].min().strftime('%d %B %Y')
tgl_akhir = df['tanggal_daftar'].max().strftime('%d %B %Y')

print(f"Tanggal pendaftaran paling awal : {tgl_awal}")
print(f"Tanggal pendaftaran paling akhir: {tgl_akhir}")

# Expected: rentang pendaftaran berada di tahun 2025

Tanggal pendaftaran paling awal : 01 February 2025
Tanggal pendaftaran paling akhir: 31 May 2025

---
## Bagian C — Kamus data

Kamus data adalah satu baris penjelasan untuk setiap kolom. Bangkitkan kerangkanya dengan kode, isi maknanya sendiri.

In [ ]:
# TODO C1 — bangkitkan kerangka kamus data
# Buat DataFrame bernama 'kamus' dengan kolom:
#   nama_kolom, tipe_data, nilai_unik, nilai_kosong, contoh_nilai
# lalu tambahkan empat kolom kosong yang akan diisi manual:
#   deskripsi, skala_pengukuran, kategori_data_pribadi, tindakan_penanganan
kamus = pd.DataFrame({
    'nama_kolom': df.columns,
    'tipe_data': [df[col].dtype for col in df.columns],
    'nilai_unik': [df[col].nunique() for col in df.columns],
    'nilai_kosong': [df[col].isnull().sum() for col in df.columns],
    'contoh_nilai': [df[col].dropna().iloc[0] for col in df.columns]
})

kolom_manual = [
    'deskripsi',
    'skala_pengukuran',
    'kategori_data_pribadi',
    'tindakan_penanganan'
]

for col in kolom_manual:
    kamus[col] = None

print("Ukuran DataFrame kamus:", kamus.shape)
display(kamus)

# Expected: 28 baris x 9 kolom

Ukuran DataFrame kamus: (28, 9)

,nama_kolom,tipe_data,nilai_unik,nilai_kosong,contoh_nilai,deskripsi,skala_pengukuran,kategori_data_pribadi,tindakan_penanganan
0,id_peserta,object,620,0,PLT-2025-1309,None,None,None,None
1,nama_lengkap,object,450,0,Ratna Hidayat,None,None,None,None
2,nik_dummy,int64,620,0,99991405899249,None,None,None,None
3,no_hp,float64,611,9,80004260813.0,None,None,None,None
4,email,object,450,0,ratna.hidayat@contoh.example,None,None,None,None
5,alamat_jalan,object,620,0,Jl. Cempaka No. 106 RT 02/RW 10,None,None,None,None
6,kelurahan,object,26,0,Sukatani,None,None,None,None
7,kecamatan,object,19,0,Tapos,None,None,None,None
8,kota,object,1,0,Depok,None,None,None,None
9,tanggal_lahir,datetime64[ns],598,0,1989-05-14 00:00:00,None,None,None,None
10,jenis_kelamin,object,2,0,P,None,None,None,None
11,pendidikan_terakhir,category,6,0,SMP,None,None,None,None
12,status_disabilitas,object,2,0,Tidak,None,None,None,None
13,jumlah_anak,int64,5,0,3,None,None,None,None
14,penghasilan_pribadi_bulanan,int64,110,0,500000,None,None,None,None
15,nama_usaha,object,185,0,CV Mandiri Jaya,None,None,None,None
16,kategori_usaha,object,5,0,Kuliner,None,None,None,None
17,produk_utama,object,19,0,Roti dan kue,None,None,None,None
18,lama_usaha_tahun,float64,119,0,12.8,None,None,None,None
19,jumlah_karyawan,int64,11,0,4,None,None,None,None
20,omzet_usaha_bulanan,int64,293,0,2950000,None,None,None,None
21,pernah_ikut_pelatihan,object,2,0,Tidak,None,None,None,None
22,kanal_pendaftaran,object,4,0,Datang langsung,None,None,None,None
23,tanggal_daftar,datetime64[ns],120,0,2025-04-04 00:00:00,None,None,None,None
24,kehadiran_persen,int64,46,0,75,None,None,None,None
25,skor_prates,int64,64,0,52,None,None,None,None
26,skor_pascates,float64,64,34,67.0,None,None,None,None
27,tingkat_kepuasan,float64,28,18,5.0,None,None,None,None

In [ ]:
# TODO C2 — kolom mana yang punya nilai kosong?
# Tampilkan hanya baris kamus yang nilai_kosong-nya lebih dari 0
kamus_kosong = kamus[kamus['nilai_kosong'] > 0]

display(kamus_kosong)

# Expected: tepat 3 kolom yang punya nilai kosong

,nama_kolom,tipe_data,nilai_unik,nilai_kosong,contoh_nilai,deskripsi,skala_pengukuran,kategori_data_pribadi,tindakan_penanganan
3,no_hp,float64,611,9,80004260813.0,None,None,None,None
26,skor_pascates,float64,64,34,67.0,None,None,None,None
27,tingkat_kepuasan,float64,28,18,5.0,None,None,None,None

### TODO C3 — isi kamus untuk lima kolom

Lengkapi tabel berikut. Deskripsi ditulis sebagai kalimat lengkap, bukan pengulangan nama kolom.

| Kolom | Deskripsi | Skala | Satuan |
|---|---|---|---|
| `lama_usaha_tahun` |Durasi waktu operasional usaha yang dijalankan oleh peserta sejak pertama kali didirikan|Rasio|Tahun|
| `kehadiran_persen` |Persentase tingkat kehadiran peserta dalam mengikuti seluruh rangkaian sesi pelatihan UMKM|Rasio|Persen|
| `skor_pascates` |Nilai evaluasi pemahaman materi yang diperoleh peserta setelah menyelesaikan kegiatan pelatihan.|Interval|Poin|
| `kanal_pendaftaran` |Media atau jalur komunikasi yang digunakan peserta untuk mendaftarkan diri pada program pelatihan.|Nominal| |
| `jumlah_anak` |Jumlah anak yang peserta dimiliki saat ini|Rasio|Orang|

---
## Bagian D — Menandai data pribadi

| Kategori | Artinya |
|---|---|
| **pengenal langsung** | Sendirian sudah menunjuk ke satu orang |
| **quasi-identifier** | Sendirian aman, gabungannya menunjuk ke satu orang |
| **data spesifik** | Bocornya merugikan lebih berat (kesehatan, keuangan pribadi, data anak) |
| **bukan data pribadi** | Tidak menunjuk ke orang; inilah bahan analisis |

In [5]:
# TODO D1 — susun tabel penandaan Anda sendiri
# Buat dictionary bernama PENANDAAN berisi pasangan:
#     'nama_kolom': ('kategori', 'tindakan')
# Tindakan yang tersedia: 'hapus', 'hash', 'generalisasi', 'pertahankan'
# Kolom yang tidak Anda daftarkan dianggap 'bukan data pribadi' + 'pertahankan'.
#
# Lalu bangun DataFrame 'tanda' dengan kolom: nama_kolom, kategori, tindakan
# dan cetak jumlah kolom per kategori.
# Expected: pengenal langsung >= 5 kolom; data spesifik >= 3 kolom

PENANDAAN = {
    # pengenal langsung (>= 5 kolom)
    'id_peserta': ('pengenal langsung', 'hash'),
    'nama_lengkap': ('pengenal langsung', 'hapus'),
    'nik_dummy': ('pengenal langsung', 'hapus'),
    'no_hp': ('pengenal langsung', 'hapus'),
    'email': ('pengenal langsung', 'hapus'),
    'alamat_jalan': ('pengenal langsung', 'hapus'),
    'nama_usaha': ('pengenal langsung', 'hapus'),

    # data spesifik (>= 3 kolom)
    'status_disabilitas': ('data spesifik', 'pertahankan'),
    'penghasilan_pribadi_bulanan': ('data spesifik', 'generalisasi'),
    'jumlah_anak': ('data spesifik', 'pertahankan'),

    # quasi-identifier
    'tanggal_lahir': ('quasi-identifier', 'generalisasi'),
    'jenis_kelamin': ('quasi-identifier', 'pertahankan'),
    'pendidikan_terakhir': ('quasi-identifier', 'pertahankan'),
    'kelurahan': ('quasi-identifier', 'generalisasi'),
    'kecamatan': ('quasi-identifier', 'generalisasi'),
    'kota': ('quasi-identifier', 'pertahankan'),
}

# Bangun DataFrame 'tanda'[cite: 2]
# Kolom yang tidak didaftarkan otomatis dianggap 'bukan data pribadi' + 'pertahankan'[cite: 2]
data_tanda = []
for col in df.columns:
    if col in PENANDAAN:
        kategori, tindakan = PENANDAAN[col]
    else:
        kategori, tindakan = 'bukan data pribadi', 'pertahankan'
    data_tanda.append({
        'nama_kolom': col,
        'kategori': kategori,
        'tindakan': tindakan
    })

tanda = pd.DataFrame(data_tanda)

# Cetak jumlah kolom per kategori[cite: 2]
print(tanda['kategori'].value_counts())

# Tampilkan DataFrame tanda
display(tanda)

kategori
bukan data pribadi    12
pengenal langsung      7
quasi-identifier       6
data spesifik          3
Name: count, dtype: int64

                     nama_kolom            kategori      tindakan
0                    id_peserta   pengenal langsung          hash
1                  nama_lengkap   pengenal langsung         hapus
2                     nik_dummy   pengenal langsung         hapus
3                         no_hp   pengenal langsung         hapus
4                         email   pengenal langsung         hapus
5                  alamat_jalan   pengenal langsung         hapus
6                     kelurahan    quasi-identifier  generalisasi
7                     kecamatan    quasi-identifier  generalisasi
8                          kota    quasi-identifier   pertahankan
9                 tanggal_lahir    quasi-identifier  generalisasi
10                jenis_kelamin    quasi-identifier   pertahankan
11          pendidikan_terakhir    quasi-identifier   pertahankan
12           status_disabilitas       data spesifik   pertahankan
13                  jumlah_anak       data spesifik   pertahankan
14  penghasilan_pribadi_bulanan       data spesifik  generalisasi
15                   nama_usaha   pengenal langsung         hapus
16               kategori_usaha  bukan data pribadi   pertahankan
17                 produk_utama  bukan data pribadi   pertahankan
18             lama_usaha_tahun  bukan data pribadi   pertahankan
19              jumlah_karyawan  bukan data pribadi   pertahankan
20          omzet_usaha_bulanan  bukan data pribadi   pertahankan
21        pernah_ikut_pelatihan  bukan data pribadi   pertahankan
22            kanal_pendaftaran  bukan data pribadi   pertahankan
23               tanggal_daftar  bukan data pribadi   pertahankan
24             kehadiran_persen  bukan data pribadi   pertahankan
25                  skor_prates  bukan data pribadi   pertahankan
26                skor_pascates  bukan data pribadi   pertahankan
27             tingkat_kepuasan  bukan data pribadi   pertahankan

### TODO D2 — pertanggungjawabkan tiga keputusan

Tiga kolom berikut sering diperdebatkan. Tulis keputusan Anda **beserta alasannya**.

| Kolom | Kategori pilihan Anda | Tindakan | Alasan |
|---|---|---|---|
| `nama_usaha` | Pengenal langsung|hapus |informasi tersebut dapat langsung mengidentifikasi nama pemilik |
| `omzet_usaha_bulanan` |bukan data pribadi | pertahankan| Informasi ini merupakan data finansial unit usaha, bukan identitas orang/pribadi|
| `id_peserta` | pengenal langsung| hash| id_peserta bertindak sebagai identifier individual.|

> Petunjuk untuk `nama_usaha`: bayangkan seseorang mencari nama itu di mesin pencari.
> Petunjuk untuk `omzet_usaha_bulanan`: apakah ini data tentang **orang** atau tentang **usaha**?
> Petunjuk untuk `id_peserta`: apakah Anda masih perlu membedakan satu baris dari baris lain?

---
## Bagian E — Menerapkan tiga tindakan

In [6]:
# TODO E1 — HAPUS
# Buat DataFrame baru bernama 'aman' yang sudah membuang semua kolom bertindakan 'hapus'.
# Cetak berapa kolom yang dibuang dan berapa yang tersisa.

kolom_dihapus = tanda[tanda['tindakan'] == 'hapus']['nama_kolom'].tolist()

aman = df.drop(columns=kolom_dihapus).copy()

jumlah_dihapus = len(kolom_dihapus)
jumlah_tersisa = aman.shape[1]

print(f"Jumlah kolom yang dibuang : {jumlah_dihapus}")
print(f"Jumlah kolom yang tersisa : {jumlah_tersisa}")

Jumlah kolom yang dibuang : 6
Jumlah kolom yang tersisa : 22

In [7]:
# TODO E2 — HASH
# Tulis fungsi samarkan(nilai, garam) yang mengembalikan 12 karakter pertama
# dari sha256(garam + nilai). Kembalikan np.nan bila nilainya kosong.
# Terapkan pada kolom yang Anda beri tindakan 'hash'.
# Expected: nilai asli dan hasil hash berbeda, dan nilai asli yang sama menghasilkan hash yang sama

import hashlib

# 1. Definisikan fungsi samarkan(nilai, garam)
def samarkan(nilai, garam="rahasia_umkm_2025"):
    if pd.isna(nilai) or nilai == "" or nilai is None:
        return np.nan

    # Gabungkan garam + nilai
    teks_gabungan = str(garam) + str(nilai)

    # Hitung SHA-256 dan ambil 12 karakter pertama
    hash_object = hashlib.sha256(teks_gabungan.encode('utf-8'))
    return hash_object.hexdigest()[:12]

kolom_hash = tanda[tanda['tindakan'] == 'hash']['nama_kolom'].tolist()

for col in kolom_hash:
    if col in aman.columns:
        aman[col] = aman[col].apply(samarkan)

print("Kolom yang di-hash:", kolom_hash)
display(aman[kolom_hash].head())

Kolom yang di-hash: ['id_peserta']

     id_peserta
0  4d17a905d296
1  46a7f7d8f538
2  158aa39b530d
3  3e5df8cfb613
4  568794a7feee

In [8]:
# TODO E3 — buktikan hash bersifat konsisten dan tidak terbaca
# a. Hash dua kali nilai yang sama, tunjukkan hasilnya identik
# b. Hash dua nilai berbeda, tunjukkan hasilnya berbeda

nilai_1 = "PLT-2025-1309"
nilai_2 = "PLT-2025-1512"

#nilai yang sama
hash_1a = samarkan(nilai_1)
hash_1b = samarkan(nilai_1)

print("--- a. Pembuktian Konsistensi (Nilai Sama) ---")
print(f"Nilai Asli  : {nilai_1}")
print(f"Hasil Hash 1: {hash_1a}")
print(f"Hasil Hash 2: {hash_1b}")
print(f"Apakah Hasil Identik? {hash_1a == hash_1b}\n")

#nilai berbeda
hash_2 = samarkan(nilai_2)

print("--- b. Pembuktian Keunikan (Nilai Berbeda) ---")
print(f"Nilai 1 : {nilai_1} -> Hash: {hash_1a}")
print(f"Nilai 2 : {nilai_2} -> Hash: {hash_2}")
print(f"Apakah Hasil Berbeda? {hash_1a != hash_2}")

--- a. Pembuktian Konsistensi (Nilai Sama) ---
Nilai Asli  : PLT-2025-1309
Hasil Hash 1: 4d17a905d296
Hasil Hash 2: 4d17a905d296
Apakah Hasil Identik? True

--- b. Pembuktian Keunikan (Nilai Berbeda) ---
Nilai 1 : PLT-2025-1309 -> Hash: 4d17a905d296
Nilai 2 : PLT-2025-1512 -> Hash: 46a7f7d8f538
Apakah Hasil Berbeda? True

**Jawaban Anda:** kalau `GARAM` ikut ter-*commit* ke GitHub, apa yang masih terlindungi dan apa yang tidak?

_Hash tidak lagi tahan terhadap serangan brute-force atau dictionary attack, karena peretas dapat meng-hash semua kemungkinan kombinasi (seperti ID atau NIK) untuk mencocokkan nilai aslinya. Namun, data tersebut masih terlindungi dari dekripsi langsung secara matematis karena fungsi SHA-256 bersifat satu arah (one-way)._

In [13]:
# TODO E4 — GENERALISASI
# a. Hitung usia peserta pada tanggal acuan 1 September 2025
# b. Buat kolom 'kelompok_umur' dengan batas: <25, 25-34, 35-44, 45-54, 55+
# c. Buang kolom tanggal_lahir dan kelurahan dari 'aman'
# d. Rapikan kolom kecamatan yang sebagian tertulis KAPITAL
# Expected: kelompok terbanyak adalah 35-44; kecamatan punya tepat 10 nilai unik

ACUAN = pd.Timestamp('2025-09-01')

#Hitung usia peserta pada tanggal acuan 1 September 2025
tgl_lahir = pd.to_datetime(aman['tanggal_lahir'])
belum_ulang_tahun = (tgl_lahir.dt.month > ACUAN.month) | (
    (tgl_lahir.dt.month == ACUAN.month) & (tgl_lahir.dt.day > ACUAN.day)
)
aman['usia'] = ACUAN.year - tgl_lahir.dt.year - belum_ulang_tahun.astype(int)

#Buat kolom 'kelompok_umur' dengan batas: <25, 25-34, 35-44, 45-54, 55+
bins = [-np.inf, 24, 34, 44, 54, np.inf]
labels = ['<25', '25-34', '35-44', '45-54', '55+']
aman['kelompok_umur'] = pd.cut(aman['usia'], bins=bins, labels=labels)

#Buang kolom tanggal_lahir dan kelurahan dari 'aman'
aman = aman.drop(columns=['tanggal_lahir', 'kelurahan'])

#Rapikan kolom kecamatan yang sebagian tertulis KAPITAL
aman['kecamatan'] = aman['kecamatan'].str.title()

print("Distribusi kelompok umur:")
print(aman['kelompok_umur'].value_counts().sort_index())

print(f"\nJumlah kecamatan unik: {aman['kecamatan'].nunique()}")

Distribusi kelompok umur:
kelompok_umur
<25       53
25-34    153
35-44    267
45-54    108
55+       39
Name: count, dtype: int64

Jumlah kecamatan unik: 10

---
## Bagian F — Memeriksa sisa risiko

Menghapus nama belum tentu cukup. Untuk setiap kombinasi quasi-identifier, hitung berapa orang yang punya kombinasi sama. Nilai terkecil disebut **k**. Target kelas ini: **k ≥ 5**.

In [14]:
# TODO F1 — tulis fungsi cek_k(data, kolom)
# Kembalikan Series berisi: k (grup terkecil), grup berisi 1 orang, total grup

def cek_k(data, kolom):
    grup_counts = data.groupby(kolom, observed=True).size()

    k_min = grup_counts.min()
    grup_1_orang = (grup_counts == 1).sum()
    total_grup = len(grup_counts)

    return pd.Series({
        'k': k_min,
        'grup_berisi_1_orang': grup_1_orang,
        'total_grup': total_grup
    })

# Menguji k-anonymity pada kolom quasi-identifier
kolom_qi = ['kecamatan', 'kelompok_umur', 'jenis_kelamin', 'pendidikan_terakhir']
hasil_cek = cek_k(aman, kolom_qi)
print(hasil_cek)

k                        1
grup_berisi_1_orang    138
total_grup             266
dtype: int64

In [15]:
# TODO F2 — ukur risiko SEBELUM penanganan
# Gunakan data asli df dengan kolom:
#   ['kelurahan', 'jenis_kelamin', 'pendidikan_terakhir', 'tanggal_lahir']
# Expected: k = 1 dan SELURUH 620 baris berada di grup berisi satu orang

kolom_sebelum = ['kelurahan', 'jenis_kelamin', 'pendidikan_terakhir', 'tanggal_lahir']

risiko_sebelum = cek_k(df, kolom_sebelum)

print("Hasil pengukuran risiko SEBELUM penanganan:")
print(risiko_sebelum)

Hasil pengukuran risiko SEBELUM penanganan:
k                        1
grup_berisi_1_orang    620
total_grup             620
dtype: int64

**Jawaban Anda:** keempat kolom itu tidak memuat nama maupun nomor telepon. Jelaskan dalam dua kalimat mengapa hasilnya tetap berbahaya.

_(kombinasi detail lokasi, demografi, dan tanggal lahir secara bersamaan menjadi pengenal tidak langsung yang sangat unik.)_

In [17]:
# TODO F3 — ukur risiko SESUDAH generalisasi
# Gunakan 'aman' dengan kolom:
#   ['kecamatan', 'jenis_kelamin', 'pendidikan_terakhir', 'kelompok_umur']
# Expected: jumlah grup berisi satu orang turun banyak, tetapi k masih 1

kolom_sesudah = ['kecamatan', 'jenis_kelamin', 'pendidikan_terakhir', 'kelompok_umur']

risiko_sesudah = cek_k(aman, kolom_sesudah)

print("Hasil pengukuran risiko sesudah generalisasi:")
print(risiko_sesudah)

Hasil pengukuran risiko sesudah generalisasi:
k                        1
grup_berisi_1_orang    138
total_grup             266
dtype: int64

In [18]:
# TODO F4 — TANTANGAN: capai k >= 5
# Generalisasikan lebih jauh sampai k >= 5, dengan MEMPERTAHANKAN sebanyak mungkin informasi.
# Anda boleh: memperlebar kelompok umur, menggabungkan kecamatan kecil menjadi 'Lainnya',
# atau mengeluarkan satu kolom dari daftar quasi-identifier.
# Catat setiap pilihan dan dampaknya terhadap k.
# Petunjuk: ada lebih dari satu jawaban benar. Yang dinilai adalah alasannya.

bins_f4 = [-np.inf, 34, np.inf]
labels_f4 = ['<35', '35+']
aman['kelompok_umur_f4'] = pd.cut(aman['usia'], bins=bins_f4, labels=labels_f4)

top_4_kecamatan = ['Pancoran Mas', 'Sukmajaya', 'Cimanggis', 'Beji']
aman['kecamatan_f4'] = aman['kecamatan'].apply(
    lambda x: x if x in top_4_kecamatan else 'Lainnya'
)

qi_f4 = ['kecamatan_f4', 'jenis_kelamin', 'kelompok_umur_f4']

risiko_f4 = cek_k(aman, qi_f4)

print("=== HASIL PENGUKURAN RISIKO (TODO F4) ===")
print(risiko_f4)

=== HASIL PENGUKURAN RISIKO (TODO F4) ===
k                       9
grup_berisi_1_orang     0
total_grup             20
dtype: int64

**Jawaban Anda:** tulis kombinasi yang Anda pilih, nilai k yang dicapai, dan informasi apa yang Anda korbankan untuk mencapainya.

_(nilai k yang berhasil dicapai adalah k = 9 (memenuhi target k >= 5). Informasi yang dikorbankan untuk mencapai tingkat privasi tersebut adalah detail presisi tingkat pendidikan peserta, kerincian 6 kecamatan kecil yang digabung menjadi kategori 'Lainnya', serta rentang umur spesifik yang disederhanakan menjadi 2 kelompok saja.)_

In [19]:
# TODO F5 — sel kecil pada tabel agregat
# a. Buat tabel silang jumlah peserta menurut kecamatan x kategori_usaha
# b. Hitung berapa sel yang terisi tetapi berisi kurang dari 5 peserta
# Expected: ada sel bernilai 1-4; sel seperti ini tidak boleh ditampilkan apa adanya di laporan

tabel_silang = pd.crosstab(aman['kecamatan'], aman['kategori_usaha'])

sel_kecil = ((tabel_silang > 0) & (tabel_silang < 5)).sum().sum()

print("Tabel Silang (Kecamatan x Kategori Usaha):")
display(tabel_silang)

print(f"\nJumlah sel terisi yang kurang dari 5 peserta: {sel_kecil}")

Tabel Silang (Kecamatan x Kategori Usaha):

kategori_usaha  Fesyen  Jasa Digital  Kriya  Kuliner  Pertanian
kecamatan
Beji                14            10     15       42          6
Bojongsari           7             5      4       23          2
Cimanggis           16             8     15       44          7
Cinere              16            11      8       23          9
Cipayung             4             6      5       10          1
Limo                10             4     10       15          4
Pancoran Mas        25            12     19       31         12
Sawangan             5             3      3       10          2
Sukmajaya           22            14     11       36         12
Tapos               11             5     11       16          6

Jumlah sel terisi yang kurang dari 5 peserta: 9

---
## Bagian G — Diterapkan pada proyek tim (dikerjakan di luar kelas)

Bagian ini adalah isi **M1**. Kerjakan bersama tim pada dataset proyek Anda sendiri.

### G1 — Pertanyaan analisis
Tulis **3–5 pertanyaan** yang lolos tiga uji. Untuk setiap pertanyaan, sebutkan kolom yang akan dipakai.

_(tulis di sini)_

### G2 — Provenans data
Catat lima butir berikut di README repositori tim:

| Butir | Isi |
|---|---|
| Nama sumber | |
| Tautan atau nama instansi | |
| Tanggal pengambilan | |
| Lisensi atau nomor surat izin | |
| Kalimat sitasi untuk laporan | |

### G3 — Kamus data
Isi `TEMPLATE_Kamus_Data.csv` untuk **setiap** kolom dataset tim, termasuk kolom `kategori_data_pribadi` dan `tindakan_penanganan`. Simpan sebagai `data_dictionary.md` atau `.csv` di repositori.

In [ ]:
# G4 — jalankan penanganan pada data tim dan periksa nilai k
# Salin pola Bagian E dan F, ganti dataset dan nama kolomnya.
# Simpan hasilnya ke data/processed/ dan JANGAN unggah data/raw/

### G5 — Daftar periksa sebelum `git push`

- [ ] `data/raw/` masuk `.gitignore`
- [ ] Tidak ada nama, NIK, nomor telepon, surel, atau alamat di berkas mana pun
- [ ] Keluaran sel yang sempat menampilkan data pribadi sudah dibersihkan
- [ ] Garam hash tidak tertulis di dalam notebook
- [ ] Kamus data memuat kategori dan tindakan untuk setiap kolom
- [ ] Nilai k pada data yang diunggah sudah dihitung dan dicatat
- [ ] Bila masih ragu: repositori dibuat **privat**

> Menghapus berkas lalu *commit* ulang **tidak** menghilangkan data dari riwayat Git. > Periksa **sebelum** *commit* pertama.