In [2]:
import pandas as pd

FILE = 'peserta_pelatihan_umkm_2025 (1).csv'

df = pd.read_csv(FILE)

print("Ukuran data:", df.shape)
df.head(3)

FileNotFoundError: [Errno 2] No such file or directory: 'peserta_pelatihan_umkm_2025 (1).csv'

In [3]:
FILE = 'peserta_pelatihan_umkm_2025.csv'

df = pd.read_csv(FILE)

print(df.shape)
df.head(3)

(620, 28)

,id_peserta,nama_lengkap,nik_dummy,no_hp,email,alamat_jalan,kelurahan,kecamatan,kota,tanggal_lahir,...,lama_usaha_tahun,jumlah_karyawan,omzet_usaha_bulanan,pernah_ikut_pelatihan,kanal_pendaftaran,tanggal_daftar,kehadiran_persen,skor_prates,skor_pascates,tingkat_kepuasan
0,PLT-2025-1309,Ratna Hidayat,99991405899249,8.000426e+10,ratna.hidayat@contoh.example,Jl. Cempaka No. 106 RT 02/RW 10,Sukatani,Tapos,Depok,1989-05-14,...,12.8,4,2950000,Tidak,Datang langsung,2025-04-04,75,52,67.0,5.0
1,PLT-2025-1512,Bunga Santoso,99992410874363,8.000347e+10,bunga.santoso@contoh.example,Jl. Bougenville No. 80 RT 10/RW 02,Mampang,Pancoran Mas,Depok,1987-10-24,...,6.5,3,7750000,Tidak,Formulir daring,2025-02-02,70,59,75.0,4.9
2,PLT-2025-1360,Endah Ramadhan,99991107987303,8.000266e+10,endah.ramadhan@contoh.example,Jl. Anggrek No. 138 RT 07/RW 08,Limo,Limo,Depok,1998-07-11,...,2.5,0,7550000,Tidak,WhatsApp,2025-03-26,90,51,61.0,4.9

In [4]:
print("Nama kolom:")
print(df.columns.tolist())

print("\nTipe data setiap kolom:")
print(df.dtypes)

print("\nUkuran data:")
print(df.shape)

Nama kolom:
['id_peserta', 'nama_lengkap', 'nik_dummy', 'no_hp', 'email', 'alamat_jalan', 'kelurahan', 'kecamatan', 'kota', 'tanggal_lahir', 'jenis_kelamin', 'pendidikan_terakhir', 'status_disabilitas', 'jumlah_anak', 'penghasilan_pribadi_bulanan', 'nama_usaha', 'kategori_usaha', 'produk_utama', 'lama_usaha_tahun', 'jumlah_karyawan', 'omzet_usaha_bulanan', 'pernah_ikut_pelatihan', 'kanal_pendaftaran', 'tanggal_daftar', 'kehadiran_persen', 'skor_prates', 'skor_pascates', 'tingkat_kepuasan']

Tipe data setiap kolom:
id_peserta                      object
nama_lengkap                    object
nik_dummy                        int64
no_hp                          float64
email                           object
alamat_jalan                    object
kelurahan                       object
kecamatan                       object
kota                            object
tanggal_lahir                   object
jenis_kelamin                   object
pendidikan_terakhir             object
status_disabilitas              object
jumlah_anak                      int64
penghasilan_pribadi_bulanan      int64
nama_usaha                      object
kategori_usaha                  object
produk_utama                    object
lama_usaha_tahun               float64
jumlah_karyawan                  int64
omzet_usaha_bulanan              int64
pernah_ikut_pelatihan           object
kanal_pendaftaran               object
tanggal_daftar                  object
kehadiran_persen                 int64
skor_prates                      int64
skor_pascates                  float64
tingkat_kepuasan               float64
dtype: object

Ukuran data:
(620, 28)

In [5]:
# A2. Pertanyaan analisis dan kolom yang digunakan

pertanyaan_analisis = [
    {
        "pertanyaan": "Apakah tingkat pendidikan peserta berkaitan dengan besarnya omzet usaha bulanan?",
        "kolom": ["pendidikan_terakhir", "omzet_usaha_bulanan"]
    },
    {
        "pertanyaan": "Apakah lama usaha berhubungan dengan besarnya omzet usaha bulanan?",
        "kolom": ["lama_usaha_tahun", "omzet_usaha_bulanan"]
    },
    {
        "pertanyaan": "Bagaimana hubungan skor prates dengan skor pascates peserta pelatihan?",
        "kolom": ["skor_prates", "skor_pascates"]
    }
]

for i, item in enumerate(pertanyaan_analisis, 1):
    print(f"{i}. {item['pertanyaan']}")
    print("   Kolom:", ", ".join(item["kolom"]))
    print()

1. Apakah tingkat pendidikan peserta berkaitan dengan besarnya omzet usaha bulanan?
   Kolom: pendidikan_terakhir, omzet_usaha_bulanan

2. Apakah lama usaha berhubungan dengan besarnya omzet usaha bulanan?
   Kolom: lama_usaha_tahun, omzet_usaha_bulanan

3. Bagaimana hubungan skor prates dengan skor pascates peserta pelatihan?
   Kolom: skor_prates, skor_pascates

In [6]:
# A3. Mencari kolom yang mengandung kata "omzet"

kolom_omzet = [col for col in df.columns if "omzet" in col.lower()]

print("Kolom yang mengandung kata 'omzet':")
print(kolom_omzet)

Kolom yang mengandung kata 'omzet':
['omzet_usaha_bulanan']

In [14]:
# TODO E1 — HAPUS

kolom_hapus = tanda.loc[tanda['tindakan'] == 'hapus', 'nama_kolom'].tolist()

aman = df.drop(columns=kolom_hapus)

print("Kolom yang dibuang:", kolom_hapus)
print("Jumlah kolom yang dibuang:", len(kolom_hapus))
print("Jumlah kolom yang tersisa:", aman.shape[1])

Kolom yang dibuang: ['nama_lengkap', 'alamat_jalan']
Jumlah kolom yang dibuang: 2
Jumlah kolom yang tersisa: 26

In [7]:
# B1. Melihat nama kolom dan tipe datanya

for col in df.columns:
    print(f"{col} : {df[col].dtype}")

id_peserta : object
nama_lengkap : object
nik_dummy : int64
no_hp : float64
email : object
alamat_jalan : object
kelurahan : object
kecamatan : object
kota : object
tanggal_lahir : object
jenis_kelamin : object
pendidikan_terakhir : object
status_disabilitas : object
jumlah_anak : int64
penghasilan_pribadi_bulanan : int64
nama_usaha : object
kategori_usaha : object
produk_utama : object
lama_usaha_tahun : float64
jumlah_karyawan : int64
omzet_usaha_bulanan : int64
pernah_ikut_pelatihan : object
kanal_pendaftaran : object
tanggal_daftar : object
kehadiran_persen : int64
skor_prates : int64
skor_pascates : float64
tingkat_kepuasan : float64

In [22]:
# TODO E2 — HASH

import hashlib
import numpy as np

GARAM = 'ganti-dengan-kalimat-rahasia-tim'

def samarkan(nilai, garam):
    if pd.isna(nilai) or nilai == '':
        return np.nan

    teks = str(nilai)
    hasil = hashlib.sha256((garam + teks).encode()).hexdigest()
    return hasil[:12]

# Ambil kolom yang diberi tindakan 'hash'
kolom_hash = tanda.loc[tanda['tindakan'] == 'hash', 'nama_kolom'].tolist()

# Terapkan hash
for kolom in kolom_hash:
    aman[kolom] = aman[kolom].apply(
        lambda x: samarkan(x, GARAM)
    )

print("Kolom yang di-hash:", kolom_hash)

Kolom yang di-hash: ['nik_dummy', 'email']

In [17]:
import pandas as pd
import numpy as np
import hashlib

In [18]:
# TODO E2 — HASH

GARAM = 'ganti-dengan-kalimat-rahasia-tim'

def samarkan(nilai, garam):
    if pd.isna(nilai):
        return np.nan

    teks = str(nilai)
    return hashlib.sha256(
        (garam + teks).encode()
    ).hexdigest()[:12]

kolom_hash = tanda.loc[
    tanda['tindakan'] == 'hash',
    'nama_kolom'
].tolist()

for col in kolom_hash:
    if col in aman.columns:
        aman[col] = aman[col].apply(
            lambda x: samarkan(x, GARAM)
        )

print("Kolom yang di-hash:", kolom_hash)

if kolom_hash:
    display(aman[[col for col in kolom_hash if col in aman.columns]].head())

Kolom yang di-hash: ['nik_dummy', 'email']

      nik_dummy         email
0  4246ba5f7a4f  c6d007587f02
1  45d79dc7aaba  273ce0390be4
2  0bbaedae0a32  22e490fe98b1
3  ca46fb19a745  3dc676971085
4  c6fbe37d0204  6ba24926989a

In [8]:
# B2. Mengubah kolom tanggal_daftar menjadi datetime

df['tanggal_daftar'] = pd.to_datetime(df['tanggal_daftar'], errors='coerce')

print(df['tanggal_daftar'].dtype)
print(df['tanggal_daftar'].head())

datetime64[ns]
0   2025-04-04
1   2025-02-02
2   2025-03-26
3   2025-05-11
4   2025-05-05
Name: tanggal_daftar, dtype: datetime64[ns]

In [9]:
# B3. Mengecek tanggal paling awal dan paling akhir

print("Tanggal paling awal:", df['tanggal_daftar'].min())
print("Tanggal paling akhir:", df['tanggal_daftar'].max())

Tanggal paling awal: 2025-02-01 00:00:00
Tanggal paling akhir: 2025-05-31 00:00:00

In [19]:
# TODO E3 — UJI HASHING

nilai1 = "contoh@email.com"
nilai2 = "contoh@email.com"
nilai3 = "emaillain@gmail.com"

hash1 = samarkan(nilai1, GARAM)
hash2 = samarkan(nilai2, GARAM)
hash3 = samarkan(nilai3, GARAM)

print("Hash nilai 1 :", hash1)
print("Hash nilai 2 :", hash2)
print("Hash nilai 3 :", hash3)

print("\nHasil pengujian:")
print("Nilai 1 dan 2 sama :", hash1 == hash2)
print("Nilai 1 dan 3 berbeda :", hash1 != hash3)

Hash nilai 1 : 55ab06b2fc36
Hash nilai 2 : 55ab06b2fc36
Hash nilai 3 : 62bc4c383f7f

Hasil pengujian:
Nilai 1 dan 2 sama : True
Nilai 1 dan 3 berbeda : True

In [24]:
# TODO E4 — GENERALISASI

ACUAN = pd.Timestamp('2025-09-01')

# a. Hitung usia peserta
aman['usia'] = ACUAN.year - aman['tanggal_lahir'].dt.year

# Kurangi 1 jika ulang tahun belum terjadi pada tanggal acuan
belum_ulang_tahun = (
    (aman['tanggal_lahir'].dt.month > ACUAN.month) |
    (
        (aman['tanggal_lahir'].dt.month == ACUAN.month) &
        (aman['tanggal_lahir'].dt.day > ACUAN.day)
    )
)

aman.loc[belum_ulang_tahun, 'usia'] -= 1

# b. Buat kelompok umur
aman['kelompok_umur'] = pd.cut(
    aman['usia'],
    bins=[-1, 24, 34, 44, 54, float('inf')],
    labels=['<25', '25-34', '35-44', '45-54', '55+']
)

print("Jumlah peserta per kelompok umur:")
print(aman['kelompok_umur'].value_counts().sort_index())

# c. Buang kolom tanggal_lahir dan kelurahan
aman = aman.drop(columns=['tanggal_lahir', 'kelurahan'])

# d. Rapikan penulisan kecamatan
aman['kecamatan'] = aman['kecamatan'].str.strip().str.title()

print("\nJumlah nilai unik kecamatan:", aman['kecamatan'].nunique())

AttributeError: Can only use .dt accessor with datetimelike values

In [25]:
# TODO E4 — GENERALISASI

ACUAN = pd.Timestamp('2025-09-01')

# Pastikan tanggal_lahir sudah bertipe datetime
df['tanggal_lahir'] = pd.to_datetime(
    df['tanggal_lahir'],
    errors='coerce'
)

# a. Hitung usia pada 1 September 2025
aman['usia'] = (
    ACUAN.year - df['tanggal_lahir'].dt.year
    - (
        (df['tanggal_lahir'].dt.month > ACUAN.month) |
        (
            (df['tanggal_lahir'].dt.month == ACUAN.month) &
            (df['tanggal_lahir'].dt.day > ACUAN.day)
        )
    ).astype(int)
)

# b. Buat kelompok umur
def buat_kelompok_umur(usia):
    if pd.isna(usia):
        return np.nan
    elif usia < 25:
        return '<25'
    elif usia <= 34:
        return '25-34'
    elif usia <= 44:
        return '35-44'
    elif usia <= 54:
        return '45-54'
    else:
        return '55+'

aman['kelompok_umur'] = aman['usia'].apply(buat_kelompok_umur)

# c. Buang tanggal_lahir dan kelurahan
aman = aman.drop(
    columns=['tanggal_lahir', 'kelurahan'],
    errors='ignore'
)

# d. Rapikan penulisan kecamatan
aman['kecamatan'] = aman['kecamatan'].astype(str).str.title()

# Hasil pengecekan
print("Jumlah kecamatan unik:", aman['kecamatan'].nunique())

print("\nJumlah peserta berdasarkan kelompok umur:")
print(aman['kelompok_umur'].value_counts())

print("\n5 data pertama:")
display(aman[['usia', 'kelompok_umur', 'kecamatan']].head())

Jumlah kecamatan unik: 10

Jumlah peserta berdasarkan kelompok umur:
kelompok_umur
35-44    267
25-34    153
45-54    108
<25       53
55+       39
Name: count, dtype: int64

5 data pertama:

   usia kelompok_umur     kecamatan
0    36         35-44         Tapos
1    37         35-44  Pancoran Mas
2    27         25-34          Limo
3    41         35-44    Bojongsari
4    52         45-54     Sukmajaya

In [10]:
# C. Data Dictionary (Kamus Data)

kamus_data = pd.DataFrame({
    'Nama Kolom': df.columns,
    'Tipe Data': df.dtypes.astype(str).values,
    'Jumlah Data': df.notna().sum().values,
    'Jumlah Kosong': df.isna().sum().values
})

kamus_data

                     Nama Kolom       Tipe Data  Jumlah Data  Jumlah Kosong
0                    id_peserta          object          620              0
1                  nama_lengkap          object          620              0
2                     nik_dummy           int64          620              0
3                         no_hp         float64          611              9
4                         email          object          620              0
5                  alamat_jalan          object          620              0
6                     kelurahan          object          620              0
7                     kecamatan          object          620              0
8                          kota          object          620              0
9                 tanggal_lahir          object          620              0
10                jenis_kelamin          object          620              0
11          pendidikan_terakhir          object          620              0
12           status_disabilitas          object          620              0
13                  jumlah_anak           int64          620              0
14  penghasilan_pribadi_bulanan           int64          620              0
15                   nama_usaha          object          620              0
16               kategori_usaha          object          620              0
17                 produk_utama          object          620              0
18             lama_usaha_tahun         float64          620              0
19              jumlah_karyawan           int64          620              0
20          omzet_usaha_bulanan           int64          620              0
21        pernah_ikut_pelatihan          object          620              0
22            kanal_pendaftaran          object          620              0
23               tanggal_daftar  datetime64[ns]          620              0
24             kehadiran_persen           int64          620              0
25                  skor_prates           int64          620              0
26                skor_pascates         float64          586             34
27             tingkat_kepuasan         float64          602             18

In [11]:
# D. Identifikasi kolom yang berpotensi mengandung data pribadi

kata_kunci_pribadi = [
    'nama',
    'nik',
    'email',
    'telepon',
    'no_hp',
    'alamat'
]

kolom_pribadi = [
    col for col in df.columns
    if any(kata in col.lower() for kata in kata_kunci_pribadi)
]

print("Kolom yang berpotensi mengandung data pribadi:")
for col in kolom_pribadi:
    print("-", col)

Kolom yang berpotensi mengandung data pribadi:
- nama_lengkap
- nik_dummy
- no_hp
- email
- alamat_jalan
- nama_usaha

In [12]:
# E. Membuat salinan data untuk proses perlindungan data pribadi

df_aman = df.copy()

print("Data asli :", df.shape)
print("Data salinan :", df_aman.shape)

Data asli : (620, 28)
Data salinan : (620, 28)

In [13]:
# TODO D1 — Menandai data pribadi

PENANDAAN = {
    'nama_lengkap': ('pengenal langsung', 'hapus'),
    'nik_dummy': ('pengenal langsung', 'hash'),
    'email': ('pengenal langsung', 'hash'),
    'nomor_telepon': ('pengenal langsung', 'hash'),
    'alamat_jalan': ('pengenal langsung', 'hapus'),
    'kelurahan': ('quasi-identifier', 'generalisasi'),
    'kecamatan': ('quasi-identifier', 'generalisasi'),
    'tanggal_lahir': ('quasi-identifier', 'generalisasi'),
    'jenis_kelamin': ('quasi-identifier', 'pertahankan'),
    'pendidikan_terakhir': ('quasi-identifier', 'pertahankan'),
    'omzet_usaha_bulanan': ('data spesifik', 'pertahankan'),
    'jumlah_anak': ('data spesifik', 'pertahankan'),
    'skor_prates': ('data spesifik', 'pertahankan'),
    'skor_pascates': ('data spesifik', 'pertahankan')
}

tanda = pd.DataFrame([
    {
        'nama_kolom': col,
        'kategori': PENANDAAN.get(col, ('bukan data pribadi', 'pertahankan'))[0],
        'tindakan': PENANDAAN.get(col, ('bukan data pribadi', 'pertahankan'))[1]
    }
    for col in df.columns
])

display(tanda)

print("\nJumlah kolom per kategori:")
print(tanda['kategori'].value_counts())

                     nama_kolom            kategori      tindakan
0                    id_peserta  bukan data pribadi   pertahankan
1                  nama_lengkap   pengenal langsung         hapus
2                     nik_dummy   pengenal langsung          hash
3                         no_hp  bukan data pribadi   pertahankan
4                         email   pengenal langsung          hash
5                  alamat_jalan   pengenal langsung         hapus
6                     kelurahan    quasi-identifier  generalisasi
7                     kecamatan    quasi-identifier  generalisasi
8                          kota  bukan data pribadi   pertahankan
9                 tanggal_lahir    quasi-identifier  generalisasi
10                jenis_kelamin    quasi-identifier   pertahankan
11          pendidikan_terakhir    quasi-identifier   pertahankan
12           status_disabilitas  bukan data pribadi   pertahankan
13                  jumlah_anak       data spesifik   pertahankan
14  penghasilan_pribadi_bulanan  bukan data pribadi   pertahankan
15                   nama_usaha  bukan data pribadi   pertahankan
16               kategori_usaha  bukan data pribadi   pertahankan
17                 produk_utama  bukan data pribadi   pertahankan
18             lama_usaha_tahun  bukan data pribadi   pertahankan
19              jumlah_karyawan  bukan data pribadi   pertahankan
20          omzet_usaha_bulanan       data spesifik   pertahankan
21        pernah_ikut_pelatihan  bukan data pribadi   pertahankan
22            kanal_pendaftaran  bukan data pribadi   pertahankan
23               tanggal_daftar  bukan data pribadi   pertahankan
24             kehadiran_persen  bukan data pribadi   pertahankan
25                  skor_prates       data spesifik   pertahankan
26                skor_pascates       data spesifik   pertahankan
27             tingkat_kepuasan  bukan data pribadi   pertahankan

Jumlah kolom per kategori:
kategori
bukan data pribadi    15
quasi-identifier       5
pengenal langsung      4
data spesifik          4
Name: count, dtype: int64